### ISSUE TITLE
How to skip triples with empty/bad values?

### ISSUE THREAD

**Issue by marco-brandizi** [tarql/tarql#55]
I cannot find a way to do this:

```
CONSTRUCT {
  ?URI has-property-1 ?Header1; has-property-2 ?Header2
}
WHERE {
  <A FILTER THAT SKIPS has-property-2 ?Header2 when Header2 is '' (or = <bad-value>)
}

```
URI and `Header1/2` are the columns in the CSV. One way could be to bind `Header2` to some intermediate `myHeader2`, and to avoid any binding when it's not the right value. But how to do that?

I've tried this: 

`OPTIONAL { FILTER ( ?Header2 != '' ). BIND ( ?Header2 AS ?myHeader2 )  }`

even with the `FILTER` after the `BIND`, but no luck, `myHeader2` is never bound. 

I've tried to place multiple `CONSTRUCT`(s) in the same file (documentation mentions this option), with the first one as above (nothing in `WHERE`) and this as second `CONSTRUCT`:

```
CONSTRUCT {
  ?s ?p ?o
}
WHERE {
  ?o != ''
}

```
I've also tried to swap the two `CONSTRUCT`(s), but in both cases I obtain triples like uri0 `has-property-2 ''`.

Is there an option to ignore certain values? Note that I don't mean the entire row. 
Currently I'm resigning to chain TARQL RDF result to the sparql Jena command.

**Comment by cygri** [comment]
Hi @marco-brandizi! This is probably way too late to be of any use to you. Sorry.

The variable bindings from the CSV table are injected into the main graph pattern. So, at the `...` part of `WHERE { ... }`. Given the semantics of `OPTIONAL`, they will not be visible within an `OPTIONAL` block. That's why your `BIND` doesn't do anything. `?Header2` has no value within that block.

A solution is to use `IF` to do a conditional `BIND`, instead of doing it inside an `OPTIONAL` with `FILTER`. At the top level of the `WHERE` clause:

    BIND (IF(?Header2 = '', ?nothing, ?Header2) AS ?myHeader2)

This binds `?myHeader2` only to the value of `?Header2` only if the condition `?Header2 = ''` is false.

I've added this [as an example](http://tarql.github.io/#skip-bad-values-for-a-field) to the homepage.

**Comment by marco-brandizi** [comment]
Thanks @cygri, thank you. So, I understand I can bind a variable to another variable that is unbound and I get what I want, without complaints that nothing doesn't exist. Clever!
