### ISSUE TITLE
[proposal] Removing duplicates option for construct requests

### ISSUE THREAD

**Issue by a-andreyev** [tarql/tarql#59]
As I can see, there is currently no option to remove duplicates from resulting request.

My custom solution is to pass output via [rapper librdf](http://librdf.org/raptor/rapper.html). For example

```
tarql --encoding=utf-8 --ntriples --base="my_base_url" construct.sparql ./input.csv > result.nt
rapper -i ntriples -o turtle -I "my_base_url" -f 'xmlns:some_custom_prefix="custom_prefix_uri"'result.nt > result.ttl
```

`rapper` convertion also adding `@base` prefix header to output turtle file

hope somebody will find it helpful

**Comment by cygri** [comment]
It would be easy to add a `--deduplicate` flag to Tarql that only works on output small enough to fit in memory.

But Tarql tries to stream its output so that it's not limited by available memory. Removing duplicate triples in very large output sets isn't that easy. I don't know of an easier way than writing a custom merge sort implementation that works on disk (or maybe using a library to help with that job, like [this one](https://github.com/lemire/externalsortinginjava)).

**Comment by cygri** [comment]
Another idea (via Jena's Andy Seaborne) is to remove duplicates within a sliding window of a few 1000 triples. Would be good enough for many cases, although it wouldn't guarantee unique triples.

Instead of rapper, you can also simply run `tarql --ntriples ... | sort -u`

**Comment by cygri** [comment]
Added `--dedup xxx` option. The `xxx` value is a window size in triples. If the same triple occurs multiple times within the window, only the first occurrence will be written to output.

If `xxx` is larger than the total number of generated triples, the output is guaranteed to be duplicate-free. Otherwise there may still be duplicates in theory, but this should give users good control over deduplication.

The default is no duplication to keep compatible with previous versions.

**Comment by cygri** [comment]
Thanks for the good ideas @a-andreyev, much appreciated!
